name: CI

on:
  push:
    tags: ['v*', 'v*.*', 'v*.*.*']
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v4
        with:
          php-version: 8.2
          extensions: mbstring, json
      - name: Install dependencies
        run: composer install --no-progress --no-suggest
      - name: Run tests
        run: vendor/bin/phpunit --colors=always
